### PR TITLE
Actor FSM

### PR DESCRIPTION
**Pull request by kipplesunderscore**
pull request changes the player code to be based on a new FSM.

currently the player movement has been re-implemented.

brings with it buffered jumps and coyote timing.

### CODE REVIEW

**Comment by schneediener** [comment]
Were there intended to be changes to the jump-feel beyond the implementation of coyote time and buffer? The jump feels faster, both up and down, and it seems to be a lot higher (I can now jump on top of 4 blocks). The fall in particular is back to being quite quick and heavy, which makes it quite a lot harder to grab specific blocks during a jump

RE: the states, generally looks good. I notice that if I'm standing next to a block, the state is constantly changing between idle and.. I think move? 

If a block falls on top of my head, I think I change to the fall state, but when I get on top of the block, I remain in a fall state (rather than returning to idle). Moving or jumping changes me make to the correct state (move or jump respectively). Not sure if his has implications or not

**Comment by kipplesunderscore** [comment]
The numbers on the jump variables got reset when I changed things. I have now set them to what they were previously.

state machine would constantly switch between 2 states when moving up against a wall (idle -> move ...) I have fixed this.

state machine would also switch between (idle -> fall) in certain scenarios this was due to idle state not applying gravity correctly.

**Comment by schneediener** [comment]
@kipplesunderscore 
image

I'm not able to move or jump. I've done a fresh fetch, but my input map in project settings still says ui_right. not right. so if you did change the input map names, it might not have been included in this branch?

**Comment by schneediener** [comment]
NVM it looks like it thought I had pre-existing changes for project.godot and didn't bring it. Discarded changes, fetched again, working. Testing now.

**Comment by schneediener** [comment]
Everything feels good: coyote time is good, jump buffering good. Idle/move seems much more stable when pressed against blocks now, which is great. 

When a block falls on my head from the ground (so Im on the ground then it falls) it looks good now: changes to idle when I move to the top of the block.
image


But, when a block falls on my head whilst I'm standing on another block, the same 'fall' state persists even if I'm standing still.

image

I've also noticed that if I'm standing on top of a box, and I move against another block, then let go and stand still, it leaves me in Move. It feels like when I'm ontop of boxes, my state sometimes doesn't want to change to idle (either from a move, or from 'fall' when box hits my head)

I don't know if it's a huge issue. I can still move, jump, pick up blocks, etc. So maybe we can just raise this as an issue for later, and merge? Functionally I've had a perfect time testing, so these two state-issues aren't getting in the way of gameplay.

**Pull request merged**
